fix problems with the dns resolving cache
bradfitz/gomemcache pull request #142
Opened 2021-11-05 15:50 UTC by HejVkt

There are problems with connecting to the memcash server by DNS name when changing the IP address of the server.

Due to the fact that the IP address is cached and there is no mechanism for resolving a new address (updating the cache), we get constant errors connecting to the server.

I have added some solution.

2021-11-05 16:08 UTC, HejVkt commented
@googlebot I fixed it.

2021-11-08 08:24 UTC, HejVkt commented
@googlebot I fixed it.

2022-01-06 21:51 UTC, bradfitz commented on memcache/selector.go
> +	Reresolve(addr *staticAddr) error
extending this interfaces breaks compatibility for everybody who's already implemented this interface. 

I don't think this is workable as-is.

2022-01-06 21:51 UTC, bradfitz requested changes
extending this interfaces breaks compatibility for everybody who's already implemented this interface.

I don't think this is workable as-is.

2022-01-06 22:03 UTC, closed without merging