Faster scanning of memcache responses
bradfitz/gomemcache pull request #154
Opened 2022-08-15 14:17 UTC by bboreham

Motivation for this change is at https://github.com/grafana/mimir/issues/285#issuecomment-1029143100, where a large program spends 12% of its CPU in this one function.

Re-coded `scanGetResponseLine()` using `IndexByte()` instead of `SScanf()`.
Also added a benchmark.

```
name                   old time/op    new time/op    delta
ScanGetResponseLine-4    4.06µs ± 1%    0.13µs ± 4%  -96.89%  (p=0.008 n=5+5)

name                   old alloc/op   new alloc/op   delta
ScanGetResponseLine-4      128B ± 0%       24B ± 0%  -81.25%  (p=0.008 n=5+5)

name                   old allocs/op  new allocs/op  delta
ScanGetResponseLine-4      7.00 ± 0%      1.00 ± 0%  -85.71%  (p=0.008 n=5+5)
```

This PR is broadly similar to #74, but about twice as fast on my benchmark.
The benchmark in #74 spends <2% of its time in `scanGetResponseLine()` so doesn't show the effect so well.

The partial copy of `strings.Cut()` in this PR allows the code to still build with pre-1.18 Go.

2022-10-31 21:43 UTC, bradfitz requested changes
Nice, thanks!

2022-10-31 21:43 UTC, bradfitz commented on memcache/memcache.go
>  func scanGetResponseLine(line []byte, it *Item) (size int, err error) {
This looks very testable. We should add a table of tests for this.

2022-10-31 21:43 UTC, bradfitz commented on memcache/memcache.go
> +		return int(size64), nil
a uint32 can technically overflow this int conversion on 32-bit machines. See https://go.dev/play/p/vvKbAGiHSkM

2024-10-09 13:03 UTC, pior commented
This looks like a great improvement, I think @bboreham addressed both comments, do you think you can take another look @bradfitz ?

2025-04-03 21:35 UTC, bradfitz commented
Merged, thanks!

2025-04-03 21:35 UTC, closed without merging