feat: support custom dialer
bradfitz/gomemcache pull request #158
Opened 2022-10-04 09:35 UTC by mar4uk

This is basically a copy of https://github.com/bradfitz/gomemcache/pull/86 with a fixing review comment

2022-10-04 09:38 UTC, mar4uk commented
@bradfitz if everything is ok, could you please merge this one?

2022-10-31 21:35 UTC, bradfitz commented on memcache/memcache.go
> +	// Dialer specifies a custom dialer used to dial new connections to a server.
`// DialTimeout`, not `// Dialer`.

But the more idiomatic thing to do these days would be to use `DialContext func(ctx context.Context, network, address string) (Conn, error)` and have us pass in a context instead.

2022-10-31 21:35 UTC, bradfitz requested changes
(Let's use DialContext instead)

2022-11-29 11:00 UTC, mar4uk commented
@bradfitz Thank you for your review! It definitely makes sense to use DialContext. I did changes, please take a look when have time

2023-06-11 14:56 UTC, bradfitz approved these changes

2023-06-11 14:56 UTC, merged